### ISSUE TITLE
Donation is 2?

### ISSUE THREAD

**Issue by yu-liang-kono** [ECPay/Invoice_Ruby#1]
For `InvoiceIssue` API, when `CustomerIdentifier` is not empty, it raises `ECpayInvoiceRuleViolate` exception and the message is `[Print] must be 1 and [Donation] must be 2 when [CustomerIdentifier] is given.`.

But `Donation` is either `0` or `1` in the document(v2.1.12), so what does `2` mean?

**Comment by AllennChang** [comment]
感謝您的詢問, 我們開發團隊已更新的sdk, 改善這個錯誤訊息的描述 ,  再次感謝您的詢問
